name: "Terraform Apply"

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    permissions:
      contents: read
      id-token: write

    env:
      TF_VAR_project: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "latest"

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.TFSTATE_BUCKET_NAME }}"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Manual Approval
        run: echo "Waiting for manual approval..."

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false